version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - HOST=0.0.0.0
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_API_URL=${GITHUB_API_URL}
      - OASDIFF_PATH=/usr/local/bin/oasdiff
    volumes:
      - swagger-cache:/app/swagger-cache
      - temp-files:/app/temp-files
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  swagger-cache:
  temp-files:
  redis-data:

networks:
  app-network:
    driver: bridge
